export interface Application {
    id?: number; // Optional because it's generated by the DB
    company_name: string;
    job_title: string;
    status?: string; // Optional if you have a default value in the DB
    application_date?: Date | string; // Optional if you have a default value
    job_description?: string;
    notes?: string;
    url?: string;
    created_at?: Date;
    updated_at?: Date;
    // user_id?: number; // Optional: If implementing user accounts
}

// You might also define specific types for creation or updates if needed
export type ApplicationCreationData = Omit<Application, 'id' | 'created_at' | 'updated_at'>;
export type ApplicationUpdateData = Partial<ApplicationCreationData>;